### ISSUE TITLE
Technical Difficulties error

### ISSUE THREAD

**Issue by ImPrasadM** [isaumya/razorpay-gravity-forms-updated#3]
Hello,

After uploading this plugin into my live site, showing Site is experiencing technical difficulties, can u please suggest what is the solution for that? I need to add this plugin into my live website

Thank you

**Comment by isaumya** [comment]
@ImPrasadM Can you please explain what issue you are facing as I'm using it in 2 live sites without any issues.

**Comment by ImPrasadM** [comment]
Once I activate this plugin along with gravity form it is showing Technical difficulties error, If I uninstall gravity form, then install this plugin it is working, I need both Gravity Form plugin and this plugin. Can you give me a solution ?

I am getting this error
![Untitled](https://user-images.githubusercontent.com/25503117/60569216-665f1380-9d8c-11e9-8c81-79ba5c0f0e5d.png)

Can you give me solution for this?

Thank you

**Comment by isaumya** [comment]
@ImPrasadM  If you are using cPanel based server, inside your `public_html` folder you should see an `error_log` file. Open that file and you can see why your site is throwing `ERROR 500`. It is not because of The Gravity Form plugin itself or this razorpay plugin.
The way the plugin should be used is, first install and active gravity form, enter your gravity form serial number. Then install this plugin. Hover on forms, settings you will see a section for Razorpay. Enter your api keys there and then make your form.

**Comment by ImPrasadM** [comment]
Yes, I am using cPanel based server, I will check now.

**Comment by isaumya** [comment]
@ImPrasadM let me know.

**Comment by ImPrasadM** [comment]
@isaumya sure

**Comment by ImPrasadM** [comment]
Now I am getting this error, I have checked the error log file

**Comment by ImPrasadM** [comment]
Now I am getting this error

![Staging-website-Error](https://user-images.githubusercontent.com/25503117/60582923-5dc80680-9da7-11e9-8b87-92edcaa726d5.png)

Thank You

**Comment by isaumya** [comment]
@ImPrasadM the log doesn't show any issues with gravity form or razorpay plugin. Check the file permission on your server as it is giving permission error. This has nothing to do the plugin.

**Comment by ImPrasadM** [comment]
Yea thank you so much, I will check it now.
